source 'https://rubygems.org'

gem 'tay'

# You can make extensions with no extra gems, but tay works best when
# coupled with other langauges and tools. Uncomment them gems below
# then run "bundle install"

# Allows you to run "tay watch" to automatically recompile on change
# gem 'guard-tay'

<%= options['use-haml'] ? '' : '# ' %>gem 'haml'
# gem 'sass'
<%= options['use-coffeescript'] ? '' : '# ' %>gem 'coffee-script'

# Allows you to use CommonJS requires in your script files
# See https://github.com/maccman/sprockets-commonjs
# gem 'sprockets-commonjs', '0.0.5.pre', :require => 'sprockets/commonjs'

# Enable javascript compression via "tay minify"
# gem 'uglifier'

# Enable css compression via "tay minify"
# gem 'yui-compressor'