source 'https://rubygems.org'

gem 'tay'

# You can make extensions with no extra gems, but tay works best when
# coupled with other langauges and tools. Uncomment them gems below
# then run "bundle install"

# gem 'haml'
# gem 'sass'
# gem 'coffee-script'

# Allows you to use CommonJS requires in your script files
# See https://github.com/maccman/sprockets-commonjs
# gem 'sprockets-commonjs', '0.0.5.pre', :require => 'sprockets/commonjs'
